#!/usr/bin/env python3
"""Generate the seed-boundary fixture the tracer's fold detector is tested on.

`scripts/tracer/geometry.js` has to find where a seeded edge crosses itself, and
the case worth testing is a real circuit rather than a hand-drawn bowtie. The
seeder is Python, the detector is JavaScript, so this emits the seam between
them: both edges of each case, in ENU metres.

Metres, not pixels, for two reasons. The detector runs in *pixel* space in the
page, and pixel space is an affine image of ENU — affine maps preserve which
segments cross, so testing in either is testing both. And metres let the test
say "the fold is 12 m from the Fairmont hairpin", which pixels could not.

The wide case is the point of the file. At their shipped half-widths neither
circuit folds anywhere, so a detector that always returned `[]` would pass
against them; widening Monaco until the inside of its tightest corners folds
over gives the detector something it has to actually find.

Regenerating unchanged inputs must produce no diff — `tests/test_seed_fixture.py`
asserts that, so the fixture cannot drift from the centerlines it was cut from.

    scripts/gen_seed_fixture.py            # rewrite tests/fixtures/seed_boundary.json
    scripts/gen_seed_fixture.py --check    # exit non-zero if it would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from twinkly_mockup.centerline import read_linestring_lonlat
from twinkly_mockup.enu import FlatEnu
from twinkly_mockup.seed import drop_seam_vertex, seed_boundary

REPO = Path(__file__).resolve().parent.parent
CONFIGS = REPO / "configs"
MANIFEST = CONFIGS / "circuits.json"
FIXTURE = REPO / "tests" / "fixtures" / "seed_boundary.json"

# Millimetres. Far finer than any fold the detector is asked to find, and it
# keeps the committed file stable against the last bits of a double.
ROUND_M = 3

# Monaco's asphalt is nothing like 24 m wide; this is a stress case, not a
# registration. Chosen as the smallest round half-width at which both edges
# fold, so the fixture exercises the detector on each of them.
WIDE_HALF_WIDTH_M = 12.0


def manifest_circuits() -> list[dict]:
    return json.loads(MANIFEST.read_text())["circuits"]


def case(name: str, half_width_m: float, *, shipped: bool) -> dict:
    coords, closed = drop_seam_vertex(
        read_linestring_lonlat(CONFIGS / f"{name}_centerline.geojson")
    )
    frame = FlatEnu.at(coords[0][1], coords[0][0])

    def to_m(lonlat: tuple[float, float]) -> list[float]:
        e, n = frame.to_enu(lonlat[1], lonlat[0])
        return [round(float(e), ROUND_M), round(float(n), ROUND_M)]

    seed = seed_boundary(coords, half_width_m, closed=closed)
    return {
        "circuit": name,
        "half_width_m": half_width_m,
        "shipped": shipped,
        "closed": closed,
        "centerline_m": [to_m(c) for c in coords],
        "left_m": [to_m(p) for p in seed.left],
        "right_m": [to_m(p) for p in seed.right],
        # Per-vertex miter extension: 1.0 on a straight, larger the tighter the
        # turn. Carried so the fold test can say *where* a fold is expected —
        # at the corners — without reimplementing curvature in JavaScript.
        "miter_factors": [round(f, 6) for f in seed.factors],
    }


def build() -> dict:
    cases = [
        case(c["name"], float(c["half_width_m"]), shipped=True) for c in manifest_circuits()
    ]
    cases.append(case("monaco", WIDE_HALF_WIDTH_M, shipped=False))
    return {
        "_comment": (
            "GENERATED by scripts/gen_seed_fixture.py — do not hand-edit. Seeded "
            "track edges in ENU metres about each circuit's first centerline vertex, "
            "for tests/js/geometry.test.js. The `shipped` cases use the manifest "
            "half-width and fold nowhere; the wide case exists so the fold detector "
            "is tested against geometry that actually folds."
        ),
        "round_m": ROUND_M,
        "cases": cases,
    }


def render(payload: dict) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--check", action="store_true", help="do not write; exit 1 if the fixture is stale"
    )
    args = p.parse_args(argv)

    text = render(build())
    if args.check:
        current = FIXTURE.read_text() if FIXTURE.exists() else ""
        if current != text:
            print(
                f"{FIXTURE.relative_to(REPO)} is stale — re-run scripts/gen_seed_fixture.py",
                file=sys.stderr,
            )
            return 1
        print(f"{FIXTURE.relative_to(REPO)} is up to date")
        return 0

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(text)
    cases = json.loads(text)["cases"]
    print(
        f"wrote {FIXTURE.relative_to(REPO)} ("
        + ", ".join(f"{c['circuit']}@{c['half_width_m']}m" for c in cases)
        + ")"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
