#!/usr/bin/env python3
"""Generate the golden fixture binding the tracer's JS frame transform to Python.

ADR-0004 accepts two implementations of the mosaic frame transform — Python for
the renderer, JavaScript for the tracer, because a round-trip to Python per drag
frame is not viable. This script is the other half of that bargain: Python is
the authority, and it emits lon/lat ↔ pixel pairs that `node --test` asserts the
JS reproduces.

The sample grid deliberately includes the **image corners**. That is where the
grid convergence has its longest lever arm and where a flipped θ is unmissable;
near the origin every sign convention agrees and the fixture would pin nothing.
A flipped θ doubles the error rather than cancelling it and looks entirely
plausible at every zoom level, which is precisely how `north_angle_deg: 0.0`
survived a full extraction run, a debug overlay, and an export.

Regenerating with an unchanged frame must produce no diff — `tests/
test_frame_fixture.py` asserts exactly that, so a fixture cannot drift away from
the sidecars it was cut from.

    scripts/gen_frame_fixture.py            # rewrite tests/fixtures/frame_transform.json
    scripts/gen_frame_fixture.py --check    # exit non-zero if it would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import yaml

from twinkly_mockup.mosaic import Mosaic, MosaicSidecar

REPO = Path(__file__).resolve().parent.parent
CONFIGS = REPO / "configs"
FIXTURE = REPO / "tests" / "fixtures" / "frame_transform.json"

# Sidecars that describe a real circuit raster. `example_mosaic.yaml` is a
# synthetic 200×200 fixture with no projection, so it would pin nothing.
SYNTHETIC_SIDECARS = {"example_mosaic.yaml"}

# Samples per axis across the full raster. 5 puts points on all four corners,
# all four edge midpoints, and the centre — corners first, everything else free.
SAMPLES_PER_AXIS = 5

SIDECAR_KEYS = (
    "origin_lat",
    "origin_lon",
    "origin_px",
    "m_per_px",
    "north_angle_deg",
    "utm_epsg",
    "grid_scale",
)


def shipped_sidecars() -> list[Path]:
    return sorted(p for p in CONFIGS.glob("*_mosaic.yaml") if p.name not in SYNTHETIC_SIDECARS)


def raster_extent_px(sidecar: MosaicSidecar) -> tuple[float, float]:
    """Raster width/height in pixels, recovered from the centre-pixel anchor.

    Every emitted sidecar anchors `origin_px` at the raster's exact centre, so
    the full extent is twice it. Read that way rather than from the PNG, which
    is gitignored build output and absent from a fresh clone.
    """
    return sidecar.origin_px[0] * 2.0, sidecar.origin_px[1] * 2.0


def samples_for(sidecar: MosaicSidecar) -> list[dict]:
    """Pixel-grid samples, each carrying its lon/lat and the pixel it maps back to."""
    width, height = raster_extent_px(sidecar)
    mosaic = Mosaic(np.zeros((2, 2, 3), dtype=np.uint8), sidecar)
    out = []
    for py in np.linspace(0.0, height, SAMPLES_PER_AXIS):
        for px in np.linspace(0.0, width, SAMPLES_PER_AXIS):
            lon, lat = mosaic.px_to_lonlat((float(px), float(py)))
            back_px, back_py = mosaic.lonlat_to_px(lon, lat)
            out.append(
                {
                    "lon": lon,
                    "lat": lat,
                    "px": back_px,
                    "py": back_py,
                }
            )
    return out


def build() -> dict:
    circuits = []
    for path in shipped_sidecars():
        raw = yaml.safe_load(path.read_text())
        sidecar = MosaicSidecar.model_validate(raw)
        circuits.append(
            {
                "name": path.stem.removesuffix("_mosaic"),
                "sidecar": {k: raw[k] for k in SIDECAR_KEYS if k in raw},
                "samples": samples_for(sidecar),
            }
        )
    return {
        "_comment": (
            "GENERATED by scripts/gen_frame_fixture.py — do not hand-edit. Python is "
            "the authority for the mosaic frame transform; scripts/tracer/frame.js "
            "must reproduce these pairs (tests/js/frame.test.js). Samples span the "
            "full raster including its corners, where a flipped convergence sign is "
            "unmissable."
        ),
        "samples_per_axis": SAMPLES_PER_AXIS,
        "circuits": circuits,
    }


def render(payload: dict) -> str:
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed fixture is stale",
    )
    args = p.parse_args(argv)

    text = render(build())
    if args.check:
        current = FIXTURE.read_text() if FIXTURE.exists() else ""
        if current != text:
            print(
                f"{FIXTURE.relative_to(REPO)} is stale — "
                f"re-run scripts/gen_frame_fixture.py",
                file=sys.stderr,
            )
            return 1
        print(f"{FIXTURE.relative_to(REPO)} is up to date")
        return 0

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(text)
    n = sum(len(c["samples"]) for c in json.loads(text)["circuits"])
    print(f"wrote {FIXTURE.relative_to(REPO)} ({n} samples)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
